baseURL = "https://northdurbanlions.org.za"
languageCode = "en-za"
title = "North Durban Lions Club"
theme = ["hugo-cloak-email", "beautifulhugo"]
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = false
pygmentsCodeFences = false
pygmentsCodefencesGuessSyntax = false
disqusShortname = "northdurbanlions"

[blackfriday]
  fractions = false

[markup.goldmark.renderer]
unsafe= true

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  # logo = "img/compass_round.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
   
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
#   name = "North Durban Lions Club"
#   website = "https://northdurbanlions.org.za"
   email = "info@northdurbanlions.org.za"
   facebook = "https://www.facebook.com/groups/313474242978"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#   github = "username"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = ""
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"

[[menu.main]]
    name = "Club Info"
    url = "info"
    weight = 1

[[menu.main]]
    name = "Meetings and Location"
    url = "location"
    parent = "Club Info"
    weight = 1

[[menu.main]]
    name = "Members"
    url = "members"
    parent = "Club Info"
    weight = 2

[[menu.main]]
    name = "Club Officers"
    url = "officers"
    parent = "Club Info"
    weight = 3

[[menu.main]]
    name = "Contact Details"
    url = "contact"
    parent = "Club Info"
    weight = 4

